### ISSUE TITLE
More Life-Bubbles ?

### ISSUE THREAD

**Issue by LitzeYT** [nyfrk/Settlers4-UnlimitedSelectionMod#1]
Is it possible to generate more life bubbles ? Like in your picture?

Version 1.1 ist working complete fine with all versions.

You using the Version of  the HE 2.50.1516.0 right ? It whould be no Problem for me to Patch all what i have done in an older version of the HE, so the unlimited patch is fully compatible with the community patch.

**Comment by nyfrk** [comment]
> Is it possible to generate more life bubbles ? Like in your picture?

Sure, that's quite easy actually. The selection markers/bubbles are controlled by 2 bits in the settler struct. I think it was somewhere near byte 20 (6th or 7th dword). It should be easy to find though. Just iterate the settler pool and toggle them for each settler you want to see the markers and health bubbles. In fact, you could even do this for enemy units. The game iterates the settler pool each frame. If one of the bits is found a marker / bubble struct is populated (containing screen coordinates and other data for rendering). These structs are organized in static arrays with a max capacity of 100 for each. If you want to increase that limit, you would have to provide larger arrays or implement a custom drawing routine that directly draws a marker/bubble for each settler in the selection vector (potentially bypassing the two mentioned bits and avoiding the static arrays at all).

The image was indeed made using larger buffers. I have not implemented that though, so feel invited to open a pull request. Just [remove these two patches](https://github.com/nyfrk/Settlers4-UnlimitedSelectionMod/blob/79605d5431f754a687a4ff3a0f1f02e184c33045/S4_UnlimitedSelection/cheat-unlimited-selection.cpp#L107) and add larger static buffers instead.

> You using the Version of the HE 2.50.1516.0 right ?

Yes. However, people told me that all HE versions are labeled with that version. So the only way we can differentiate them is by checksum (or maybe by timestamp?).

> It whould be no Problem for me to Patch all what i have done in an older version of the HE, so the unlimited patch is fully compatible with the community patch.

I don't think that's a problem. There should be no conflicts. However, I still discourage you from doing this kind of direct patching to the S4_Main.exe or other executables. There are many issues with this approach. Rather put your changes in a dll and make it a plugin like I demonstrated with this mod. For example, [morphys mod](https://www.gog.com/forum/the_settlers_series/settlers_iv_settler_limit_mod) you used to increase the settler limit would be a perfect fit for a separate plugin. You could even fix the buffer overflows that will eventually occur. The game speed mod would be better if it were directly a dropdown in the lobby and if it would automagically sync with other participants (or being grayed out if one player does not have the mod installed). Fixing overflows, rendering or intercepting user inputs are difficult with just byte patching the binaries. Plus, it will be easier to support the gold edition too (I just learned people were still using it).


The largest problem (basically the only source of instability) of the selection mod is still [this](https://github.com/nyfrk/Settlers4-UnlimitedSelectionMod/blob/2fa20132cc65464b26a794d74363a1a3c27668d6/S4_UnlimitedSelection/cheat-unlimited-selection.cpp#L119). It results in heap corruptions and will make the game crash at some point when more than 100 units were commanded at least once. The risk drastically increases, especially when the game releases heap resources (like when exiting the map). That's the only limiting factor from preventing us to successfully push the limit beyond 474. Moreover, i am pretty sure that this particular patch will cause desyncs when used in multiplayer. I haven't found a better alternative for it yet. A naive and simple fix that would also allow multiplayer interoperability would be to simply keep that limit intact and just rotate the selection vector by 100 elements each time a command is issued. Players would then have to hit the right mouse button multiple times to command more than 100 units (or we could simulate it with repeated PostMessage invocations). Each click would command 100 units (but not the same 100). But that solution sounds rather crude and would probably break some buttons in the UI (like patrolling). If nobody finds a proper solution for this I will probably go this route. This way we can at least let the game create multiple valid command packets instead of a single invalid one. We could then also push the limit to 1000 or 2000. 

In the near future, I will probably restructure the project anyway because people asked for gold edition support, an end scene hook example and how one could add functionality to existing UI elements and menus. So i can implement the larger buffers on that occasion too. Moreover, i plan to add a proper veh handler since the default fatal error message boxes are useless. A proper stack trace and register/stack dump for crashes would greatly improve our ability to track down bugs. I probably will have to also update the readme because people were having difficulties finding a proper way to inject the dll automatically (without my injector). I am not sure when i will do all this. I will probably have to spend an entire evening for all this.

**Comment by LitzeYT** [comment]
> > Is it possible to generate more life bubbles ? Like in your picture?
> 
> Sure, that's quite easy actually. The selection markers/bubbles are controlled by 2 bits in the settler struct. I think it was somewhere near byte 20 (6th or 7th dword). It should be easy to find though. Just iterate the settler pool and toggle them for each settler you want to see the markers and health bubbles. In fact, you could even do this for enemy units. The game iterates the settler pool each frame. If one of the bits is found a marker / bubble struct is populated (containing screen coordinates and other data for rendering). These structs are organized in static arrays with a max capacity of 100 for each. If you want to increase that limit, you would have to provide larger arrays or implement a custom drawing routine that directly draws a marker/bubble for each settler in the selection vector (potentially bypassing the two mentioned bits and avoiding the static arrays at all).
> 
> The image was indeed made using larger buffers. I have not implemented that though, so feel invited to open a pull request. Just [remove these two patches](https://github.com/nyfrk/Settlers4-UnlimitedSelectionMod/blob/79605d5431f754a687a4ff3a0f1f02e184c33045/S4_UnlimitedSelection/cheat-unlimited-selection.cpp#L107) and add larger static buffers instead.

Thanks for your answer, I will try something to work around this and then start a pull request. I have already tried before the thread but unfortunately I did not get it right. 
Why didn't you just patch it in when it was in the picture? 

> > You using the Version of the HE 2.50.1516.0 right ?
> 
> Yes. However, people told me that all HE versions are labeled with that version. So the only way we can differentiate them is by checksum (or maybe by timestamp?).

I guess Checksum whould be the Best, i have all HE Versions here, if you want to i can send you all checksums.
> 
> > It whould be no Problem for me to Patch all what i have done in an older version of the HE, so the unlimited patch is fully compatible with the community patch.
> 
> I don't think that's a problem. There should be no conflicts. However, I still discourage you from doing this kind of direct patching to the S4_Main.exe or other executables. There are many issues with this approach. Rather put your changes in a dll and make it a plugin like I demonstrated with this mod. For example, [morphys mod](https://www.gog.com/forum/the_settlers_series/settlers_iv_settler_limit_mod) you used to increase the settler limit would be a perfect fit for a separate plugin. You could even fix the buffer overflows that will eventually occur. The game speed mod would be better if it were directly a dropdown in the lobby and if it would automagically sync with other participants (or being grayed out if one player does not have the mod installed). Fixing overflows, rendering or intercepting user inputs are difficult with just byte patching the binaries. Plus, it will be easier to support the gold edition too (I just learned people were still using it).

We are already working on patching it when you use the launcher and not before or permanently. 
It is also so that we have already managed to add a dropdown in game, so that you can select the speed there.

> The largest problem (basically the only source of instability) of the selection mod is still [this](https://github.com/nyfrk/Settlers4-UnlimitedSelectionMod/blob/2fa20132cc65464b26a794d74363a1a3c27668d6/S4_UnlimitedSelection/cheat-unlimited-selection.cpp#L119). It results in heap corruptions and will make the game crash at some point when more than 100 units were commanded at least once. The risk drastically increases, especially when the game releases heap resources (like when exiting the map). That's the only limiting factor from preventing us to successfully push the limit beyond 474. Moreover, i am pretty sure that this particular patch will cause desyncs when used in multiplayer. I haven't found a better alternative for it yet. A naive and simple fix that would also allow multiplayer interoperability would be to simply keep that limit intact and just rotate the selection vector by 100 elements each time a command is issued. Players would then have to hit the right mouse button multiple times to command more than 100 units (or we could simulate it with repeated PostMessage invocations). Each click would command 100 units (but not the same 100). But that solution sounds rather crude and would probably break some buttons in the UI (like patrolling). If nobody finds a proper solution for this I will probably go this route. This way we can at least let the game create multiple valid command packets instead of a single invalid one. We could then also push the limit to 1000 or 2000.
> 
> In the near future, I will probably restructure the project anyway because people asked for gold edition support, an end scene hook example and how one could add functionality to existing UI elements and menus. So i can implement the larger buffers on that occasion too. Moreover, i plan to add a proper veh handler since the default fatal error message boxes are useless. A proper stack trace and register/stack dump for crashes would greatly improve our ability to track down bugs. I probably will have to also update the readme because people were having difficulties finding a proper way to inject the dll automatically (without my injector). I am not sure when i will do all this. I will probably have to spend an entire evening for all this.

I tried multiplayer and there were no DeSyncs yet.
Your idea sounds good, although the alternative with 5 clicks = always different packs will of course bother some people in the long run.

**Comment by nyfrk** [comment]
> Why didn't you just patch it in when it was in the picture?

I am doing this kind of tests directly in my debugger. Translating that in working C code is additional work. I can do that but probably won't make it until the weekend. Better spent some time to investigate the heap corruption of the command limit patch. Hopefully we can find a better way of fixing that! More on that below.

> I guess Checksum whould be the Best, i have all HE Versions here, if you want to i can send you all checksums.

It would be nice to have a list of all versions and their checksums somewhere published. On the other hand the fact that I'm using a different version is probably unique to my case. Probably not worth bothering with.

> It is also so that we have already managed to add a dropdown in game, so that you can select the speed there.

Sounds good!

> Your idea sounds good, although the alternative with 5 clicks = always different packs will of course bother some people in the long run.

I think we can make it such that one would not notice it. IIRC the mouse inputs to the game can be faked using PostMessage(WM_RBUTTONDOWN, ...) as the game does only process user inputs through its wnd proc. 

I am not sure where exactly the heap becomes corrupted when using a single event (ie the one mouse click method). The units to command are stored in a heap allocated memory block. The game always allocates enough memory for the units of the selection vector. However, the net event struct is never reallocated - it cannot change size. So when copying from the command to the net event struct an overflow *may* happen. But probably its caused at the consumers end. I believe that you can only send one net event per tick though. Since the net event is (probably) limited, we can always command at most 100 units per tick. We would have to prepare packets for consecutive ticks with the surplus units to circumvent that. It would be smart to push that to the games event queue. To that queue we cannot put the settlers to command since it only stores fields like "where you were clicking" and not "what units were selected". No matter what we do, we would have invest more effort and distribute the command over multiple ticks.

It is worth noting that the event struct is actually large enough to hold more units (a fact I am abusing for the mod). If we fill up all bytes that are zeroes anyway in the struct, we can put 464 settlers in a single event. If we tolerate overwriting non zero values, we can fit up to 474 settlers in the event struct. FYI, here is the struct I quickly copied from my debugger:

```c
struct NetEvent_t {
  DWORD __unk1;
  enum EventId_e : DWORD {
    COMMAND_UNITS            = 0x1396,
    MAKE_GROUP               = 0x13B1, // the x field will be the group number
    START_BUILDING           = 0x13A1,
    CHANGE_BUILDING_RADIUS   = 0x1389,
    BOMB_BULDING             = 0x138A,
    TOGGLE_BUILDING_PAUSE    = 0x138B,
    TOGGLE_BUILDING_PRIORITY = 0x138C,
    // there is much more ids...
    // note that the fields below this are mostly unionized.
  } eventId;
  WORD x;
  WORD y;
  enum NetCommand_e : WORD { // this suggests that we could combine them (altclick + patrol for example)
    normal     = 0,
    patrol     = 1,
    shiftclick = 2, // additive to previous event
    altclick   = 4,
    stop       = 8,
  } command;
  WORD __unk2;
  DWORD tick;
  DWORD __unk3[2];
  DWORD sizeOfSettlers; // size of the following array
  WORD settlers[]; // settlers affected. Usually max 100 elements, can be up to 474, its by default zeroes up to 464
};
```

**So, if you decide to invest some time: Find the consumer of that event.** Then look for the heap corruption there. I don't believe that the cause is at the producers end of the event.

However, since we need to split the command to multiple ticks anyway at some point, we could try to send events ourself. Maybe we can find a hook that could filter events and/or injects custom ones. That would enhance the things we can do drastically. We could even create completely new AI behavior with that - since they are controlled by such events too.

**Comment by nyfrk** [comment]
Sorry i did not do anything this weekend. But i spend this morning some time to reverse engineer the game even more. 

I think i found a nice way of getting the limit far beyond 2000. (basically whatever limit we want)
* Unlimited health bubbles
* No multiple mouse clicks required
* Multiplayer interoperability (you can play with players that do not use the mod)
* No more heap corruptions for 100+ unit net events
* Fully compatible to the gold edition as well
* Additional filters in the menu (like removing units from a selection that are assigned to a group, removing wounded units etc)
* DDRAW hook to draw overlays or between layers (UI, map, terrain, etc). That's useful for ESP stuff.

However, i'm thinking about releasing the patterns/hooks under a different license. I used some neat hooks to manipulate the event queues. They are of special value as other mods may use the very same hooks to accomplish totally different things. However, that would break compatibility between mods. To allow for compatibility with multiple mods it is in our best interest to keep all mods that employ these hooks open source. So I thought about creating a settlers 4 mod library that will manage the hooks and that dispatches their access to the mods. I'm still open sourcing it, although i will license the lib under LGPL or alike to ensure that every derivative work of the lib must be open sourced too. This way the community can always fix arising incompatibilities. The plugin (unlimited selection mod) will probably stay MIT licensed but will link to the new lib. Maybe i will release a binary only soon so you can test it.

**Comment by nyfrk** [comment]
I updated the readme and pushed a [preview release (v2.0)](https://github.com/nyfrk/Settlers4-UnlimitedSelectionMod/releases/latest). There are still some minor issues, but the general concept seems to work. I will release the source code later since I want to release the hooks in a shared lib to enable other plugins to use them too.

**Comment by LitzeYT** [comment]
We're getting Desyncs in the Multiplayer with version 2.0. when we're trying to get more then 100.

**Comment by nyfrk** [comment]
@LitzeYT I opened a new ticket here: #5

Should be relatively easy to fix though.
